version: '3.8'

services:
  # Django Application Service
  django_app:
    image: python:3.9-slim  # Lightweight Python image
    container_name: django_app
    restart: always
    volumes:
      - ./django_app:/app  # Mount your Django app code here
    working_dir: /app
    environment:
      - POSTGRES_DB=djangodb
      - POSTGRES_USER=djangouser
      - POSTGRES_PASSWORD=djangopassword
    command: >
      sh -c "pip install -r requirements.txt &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - postgres_db
    networks:
      - django_network

  # Nginx Service
  nginx:
    image: nginx:alpine  # Lightweight Nginx image
    container_name: nginx
    restart: always
    ports:
      - "80:80"  # Expose port 80 for HTTP traffic
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount custom Nginx configuration
      - ./static:/static  # Mount Django static files
    depends_on:
      - django_app
    networks:
      - django_network

  # PostgreSQL Database Service
  postgres_db:
    image: postgres:13-alpine  # Lightweight PostgreSQL image
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_DB=djangodb
      - POSTGRES_USER=djangouser
      - POSTGRES_PASSWORD=djangopassword
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist database data
    networks:
      - django_network

# Volumes for persistent data
volumes:
  postgres_data:

# Networks to connect services
networks:
  django_network:
    driver: bridge